### ISSUE TITLE
Add a Testimonial Page in the Website

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#1]
**The Website needs a testimonial page like in this website** [Testimonial](https://www.owenell.com/about)

**Things which has to be changed:**
1. Add a testimonial section on the website above the contact form.
2. The illustrations should not be added just simply add a Testimonial section similar to the referenced website.

**Comment by saviourcode** [comment]
May I help in fixing this issue?

**Comment by DARK-art108** [comment]
go ahead 👍 @saviourcode

**Comment by saviourcode** [comment]
And I just saw there is no normalize.css file? We could add that too for better portability between browsers.

**Comment by DARK-art108** [comment]
Just add the things which make it more awesome!! :)

**Comment by saviourcode** [comment]
Affirmative

**Comment by saviourcode** [comment]
Can we use cards with outer box shadows to enclose each testimonial? That way we can have 3 testimonials in a row!

**Comment by saviourcode** [comment]
![Screenshot (575)](https://user-images.githubusercontent.com/36518515/92335982-b4228a80-f0b9-11ea-906d-a47829b7907c.png)

Is this Testimonial Section okay?

**Comment by DARK-art108** [comment]
Add the cards!! And all the things are awesome :)

**Comment by saviourcode** [comment]
![Screenshot (577)](https://user-images.githubusercontent.com/36518515/92378127-ec11e800-f122-11ea-8672-66d63bd20d8e.png)

Card Design for testimonial, I have kept both the version with and without the cards.

**Comment by DARK-art108** [comment]
Great Work @saviourcode :)

**Comment by saviourcode** [comment]
> Great Work @saviourcode :)

Thanks a lot for your kind words and encouragement! Let's make the most beautiful site of all! @DARK-art108
