### ISSUE TITLE
Update of Header as a Image slider and Remove the present Header

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#14]
Update the header as given in the reference website [reference]( https://brenebrown.com/)

![logo](https://user-images.githubusercontent.com/53623244/92496977-738c5380-f216-11ea-8353-12b7b6bfb35d.PNG)
![header](https://user-images.githubusercontent.com/53623244/92496415-b863ba80-f215-11ea-9228-932f7ff57510.PNG)

Shift the logo to the center as in the reference website and some of the nav items to the top of the slider at the left and right of the logo but do not remove the navigation button.

And also add smooth scrolling to the items which are are present at the left and right of the logo also.

**Take a reference from the website given above for better understanding**

**Comment by saviourcode** [comment]
I am up for it!

**Comment by DARK-art108** [comment]
Go Ahead :) @saviourcode

**Comment by saviourcode** [comment]
I would like to invite other participants as well who have worked on previous issues. @ksatyarth2 @sarthakkundra @Harshita248 for speedy fix.

**Comment by ksatyarth2** [comment]
@saviourcode thank you for inviting me.
I would also love to contribute to it.

**Comment by DARK-art108** [comment]
@ksatyarth2 @sarthakkundra @Harshita248 Go Ahead 👍

**Comment by Harshita248** [comment]
Thank you @saviourcode . Would be happy to work on it

**Comment by DARK-art108** [comment]
**Thanks, @saviourcode @sarthakkundra @Harshita248 @ksatyarth2 for contributing to this pr awesome work :)**
