### ISSUE TITLE
Update  Testimonials  part by including a type of carousel and make it slide automatically.

### ISSUE THREAD

**Issue by Harshita248** [girlscript/EQEquation-Website#16]
Take a look at this https://www.w3schools.com/bootstrap/bootstrap_carousel.asp#:~:text=The%20class%3D%22carousel%22%20specifies,do%20not%20want%20this%20effect.

make the testimonial card at the center.

**Comment by Harshita248** [comment]
Make the website look appealing by taking examples from different websites.

**Comment by vanshikapandey** [comment]
I would like to work on it :)

**Comment by saviourcode** [comment]
A guide to help you understand this issue: 

1. In the Testimonial Section, currently, there are three cards in a row, 
2. Suppose in the same row we add left and right scroll button on both sides of the row then, we can create a scrollable card like effect.
3. Each time a user presses the left/right scroll button, all the three cards currently displayed get swiped left/right to be replaced with another set of 3 cards of testimonial.
4. For the mobile view, the slider will display only one card at the time and other functionalities will be the same.

**Comment by vanshikapandey** [comment]
thank you sir I will be handling it and will generate a PR asap

**Comment by saviourcode** [comment]
@vanshikapandey For any assistance, you may contact @DARK-art108 or @Harshita248 via Slack.

**Comment by vanshikapandey** [comment]
Ok sir
 The work is going on I will update you asap
