### ISSUE TITLE
Add a Custom ScrollBar in the website as Shown in the below image

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#17]
![css-scrollbar](https://user-images.githubusercontent.com/53623244/92506339-ec91a800-f222-11ea-98c0-cdc0676bbbbd.jpg)

**Comment by muskanvk** [comment]
I'd like to work on this, Could you please assign this to me ?

**Comment by DARK-art108** [comment]
Go Ahead @muskanvk :)

**Comment by Kavisha20340** [comment]
I would like to work on this. Please consider me if you ever want to reassign

**Comment by DARK-art108** [comment]
I don't see any progress in this issue do? Would you Update me regarding the current progress

**Comment by muskanvk** [comment]
Hey @DARK-art108 I am working on it but I dismantled the entire thing and its creating a lot of errors. I was looking to fix #8 with it. If you want to assign it to @Kavisha20340 you can :) It can take a little time from my end.
