### ISSUE TITLE
Add a Animation of Auto Closing of Nav Bar when user is not interacting with it.

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#19]
Setup a functionality of the auto-closing of the navbar.

**Comment by vanshikapandey** [comment]
I would like to work on this.Please assign this to me

**Comment by DARK-art108** [comment]
Go Ahead 👍

**Comment by vanshikapandey** [comment]
Thank you

**Comment by vanshikapandey** [comment]
Sir I have added the feature of auto hide I will be generating the pull
request asap

Thank you
Vanshika Pandey
Regards
