### ISSUE TITLE
Add Hover Effect over the the NavBar Items

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#2]
1. Add Hover Effect Over the NavBar Items

**Comment by saviourcode** [comment]
I can help in enchancing it.

**Comment by Harshita248** [comment]
I can help in enhancing the navbar

**Comment by DARK-art108** [comment]
Go ahead @Harshita248

**Comment by saviourcode** [comment]
@Harshita248 Make sure to pull the latest master branch, as PR #3 has been merged today.

**Comment by Harshita248** [comment]
> @Harshita248 Make sure to pull the latest master branch, as PR #3 has been merged today.

yes I have . Thank you
