### ISSUE TITLE
Create Drop-down menu style footer for Mobile View

### ISSUE THREAD

**Issue by saviourcode** [girlscript/EQEquation-Website#25]
The current footer styling for the mobile view is like this:   
<img src="https://user-images.githubusercontent.com/36518515/92581902-e5fc4280-f2ad-11ea-91c4-04b19b22bdd7.PNG" width="30%">
The task is as follows: 

- [ ] 1. Make the Left column of the footer as the drop-down menu shown in the reference picture below.
<img src="https://user-images.githubusercontent.com/36518515/92583437-edbce680-f2af-11ea-8129-213c8339f185.png" width="100%">

- [ ] 2. Place the right column of the current footer below the social media links.

**Comment by priyanshk20** [comment]
Can i take this? Please assign me this issue
