### ISSUE TITLE
Add Social Media Links on the footer.

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#4]
Add social media links with icons in the footer section

**Comment by ksatyarth2** [comment]
I can do it. Can I take this please?

**Comment by saviourcode** [comment]
I will like to take up this issue but want others to participate as well. Let's wait for other participants too.

**Comment by Garima-27** [comment]
Can I also contribute in this ?

**Comment by DARK-art108** [comment]
@ksatyarth2 go-ahead :)

**Comment by saviourcode** [comment]
> @ksatyarth2 go-ahead :)

Congratulations @ksatyarth2 for being assigned your first issue on this project!
Few Points I will like to add to help you get started with this issue:

- [ ] 1. Fork this repo according to the contributing guidelines given for this project.
- [ ] 2. For reference, you can design this kind of Social Media Footer link Column inside the footer
![gssoc](https://user-images.githubusercontent.com/36518515/92450424-0c03e300-f1d9-11ea-95de-b46a1b5f28ad.PNG)
- [ ] 3. The Social Media Logo/ Glyphs are taken from [Font Awesome](https://fontawesome.com/) Free Version only.
- [ ] 4. You will need to add Font Awesome Fonts to the Project and then only those Glyphs will display correctly.
- [ ] 5. Update your progress on this issue.

For any assistance, you may contact @DARK-art108 or me via Slack Channel.
