### ISSUE TITLE
Add the button below the About content which redirects to the page.

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#42]
The page should have a sticky navbar with a right nav button that will be implemented similar to the main page.

then all the things will be implemented as it is on this website https://www.owenell.com/ page except the bottom column buttons and footer.

the footer should be the same as the main page.

**Take a look to the reference website for understanding**

**Comment by sarthakkundra** [comment]
@DARK-art108 the issue is a little unclear as to what is actually needed to be done. Can you please explain it?

**Comment by sarthakkundra** [comment]
@DARK-art108 shouldn't we be using a framework like React, Vue or a template engine like Handlebars for a website  like this? It'll save a lot of repetitive tasks like the ones explained by @saviourcode

**Comment by yashvarshney003** [comment]
We can use also flask(Jinja template). If @DARK-art108   you agree I want to do,

**Comment by yashvarshney003** [comment]
Please reply.
