### ISSUE TITLE
All good websites have themes (dark mode & light mode) . These days it is very common to the users. I suggest to add a button which would toggle between the themes. If approved, I would like to take up this issue.

### ISSUE THREAD

**Issue by Riya-code** [girlscript/EQEquation-Website#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DARK-art108** [comment]
Go Ahead @Riya-code

**Comment by saviourcode** [comment]
@Riya-code Kindly, close thise issue as we have already merged your PR for it.

Thanks alot for contributing, more to come.

**Comment by Riya-code** [comment]
Successfully merged.
