### ISSUE TITLE
Add a Website Loading Animation Feature [Preloaders]

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#6]
Have a look at this medium article : [Animations](https://medium.muz.li/top-30-most-captivating-preloaders-for-your-website-95ed1beff99d)

We want a website loading animation similar to anyone of it.

If **Lottie animation** is implemented it would be great.

**Take a look at Lottie loading animations**

[Lottie Loaders Animation](https://lottiefiles.com/tag/loader)

**Comment by sarthakkundra** [comment]
I would like to take this @DARK-art108

**Comment by DARK-art108** [comment]
Go Ahead :)

**Comment by sarthakkundra** [comment]
working on it

**Comment by DARK-art108** [comment]
@sarthakkundra  the above merged of the preloaders has caused the navbar not responding can you again work on this :)

**Comment by DARK-art108** [comment]
I have reverted back the PR as previously it is showing the error of addEventListiner failed so before executing deploy it in your personal Heroku netlify or GitHub pages and check that everything is working or not.
