### ISSUE TITLE
Implement only the header like in the reference website https://ready.so/

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#81]
Implement only the header like in the reference website https://ready.so/ the header should have the same blur effect with Disappearing effect as we scroll down.

Points to focus on:

Implement the feature exactly the same as in the reference website.

Do not add any options or logo just add a header similar to the website

And last maintain good code quality with comments.

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by Riya-code** [comment]
Its already assigned to me :)

**Comment by Shubham-1105** [comment]
Sure

**Comment by iemprashant** [comment]
I would like to work on this issue, if it's not done Please assign it to me.

**Comment by saviourcode** [comment]
@DARK-art108 you may close this issue as it is fixed in #85
