### ISSUE TITLE
Add a Hero Section same as Referenced Website!!

### ISSUE THREAD

**Issue by DARK-art108** [girlscript/EQEquation-Website#82]
Add the Hero section as in the referenced website make sure you remove the current slider hero section and add this one!!

Referenced Website: https://www.climateneutral.org/

Hero Section:
![Capture](https://user-images.githubusercontent.com/53623244/94779098-fa7eb700-03e3-11eb-99df-dbf237569bc7.PNG)

**Comment by Shubham-1105** [comment]
interested to work

**Comment by DARK-art108** [comment]
try to deliver by tomorrow 4pm
