### ISSUE TITLE
[Bug] Top Nav Bar is Auto Open/Close not working

### ISSUE THREAD

**Issue by saviourcode** [girlscript/EQEquation-Website#88]
## Describe the bug?
Top Navbar is currently fixed to the top and does not show up when scrolling up.

## Describe how you want to fix it?
I noticed some styles to be missing the style.css file that will make the navbar working again.

## Additional Fix
Addition of the new logo to the site.

**Comment by vanshikapandey** [comment]
Sir I want to work on this issue.Please let me know more about it.
Thank you.

**Comment by saviourcode** [comment]
> Sir I want to work on this issue.Please let me know more about it.
> Thank you.

Sorry for the confusion, but this issue was fixed in the recent PR #87

**Comment by saviourcode** [comment]
@vanshikapandey If you want I will create a new issue shortly you can work on that one.

**Comment by saviourcode** [comment]
@vanshikapandey Check out #91, I just opened it up.

**Comment by saviourcode** [comment]
@DARK-art108 You may close this issue, it is fixed in #89

**Comment by vanshikapandey** [comment]
Ok sir :)
