### ISSUE TITLE
Refactoring of the Website

### ISSUE THREAD

**Issue by saviourcode** [girlscript/EQEquation-Website#91]
**Is your feature request related to a problem? Please describe.**

- [x] Check all the links in the header are working. Ex: Home button on the navbar and sidebar does not take to the hero section

- [x] Fix Font Size in the footer Section and links inside them

- [ ] Add Mobile View Footer Open/Close animation to the dropdowns

- [x] Fix Font Size in the Hero-Section of the header as well as the paragraphs

**Comment by vanshikapandey** [comment]
Sir I am interested in working on it
Please assign it to me

**Comment by saviourcode** [comment]
Go ahead @vanshikapandey , all the best!

**Comment by vanshikapandey** [comment]
Sure sir.Will update you asap
